version: '3'

volumes:
  postgres_data: {}

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always


  bot:
    build:
      context: .
      dockerfile: ./compose/class_bot/Dockerfile-dev
    volumes:
      - ./:/core_app/
    command: ["python", "./run.py"]
    environment:
      - REDIS_PORT=6379
      - NEIS_API_KEY=<API_KEY>
      - DISCORD_BOT_TOKEN=<DISCORD_BOT_TOKEN>
      - DISCORD_BOT_VERSION=1.0
    depends_on:
      - redis
    restart: always