FROM ubuntu:20.04
ENV PYTHONUNBUFFERED 0

WORKDIR /core_app
RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3 -y && apt-get install python3-pip -y
RUN apt-get install -y build-essential libssl-dev libffi-dev python3-dev libpq-dev
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && echo Asia/Seoul > /etc/timezone

ADD requirements.txt /core_app/
RUN pip3 install -r requirements.txt